blueprint:
  name: Appliance has finished
  description: Do something when an appliance (like a washing machine or dishwasher) has finished as detected by a power sensor.
  domain: automation
  input:
    power_sensor:
      name: Power Sensor
      description: "Power sensor entity (e.g. from a smart plug). Needs to have device_class: power"
      selector:
        entity:
          domain: sensor
          device_class: power
    starting_threshold:
      name: Starting power threshold
      description: "Power threshold above which we assume the appliance has started. (suggestion: 5)"
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: W
    starting_hysteresis:
      name: Starting hysteresis
      description: "Time duration the power measurement has to stay above the starting power threshold. (suggestion: 5)"
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: min
    finishing_threshold:
      name: Finishing power threshold
      description: "Power threshold below which we assume the appliance has finished. (suggestion: 5)"
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: W
    finishing_hysteresis:
      name: Finishing hysteresis
      description: "Time duration the power measurement has to stay below the finishing power threshold. (suggestion: 5)"
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: min
    actions:
      name: Actions
      description: Actions (e.g. pushing a notification, TTS announcement, ...)
      selector:
        action:

trigger:
  - platform: numeric_state
    entity_id: !input power_sensor
    for:
      minutes: !input starting_hysteresis
    above: !input starting_threshold
condition: []
action:
  - wait_for_trigger:
      - platform: numeric_state
        entity_id: !input power_sensor
        below: !input finishing_threshold
        for:
          minutes: !input finishing_hysteresis
  - choose: []
    default: !input actions
mode: single
max_exceeded: silent